import Link from "next/link";
import { ForageLogo } from "@/components/brand/ForageLogo";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-canvas text-text-primary">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <div className="mb-10">
          <Link href="/" className="inline-block mb-8">
            <ForageLogo size={24} />
          </Link>
          <h1 className="font-display font-black text-3xl mb-2">Terms of Service</h1>
          <p className="text-text-muted text-sm">Last updated: May 15, 2025</p>
        </div>

        <div className="prose prose-sm max-w-none space-y-8 text-text-secondary leading-relaxed">

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">1. Acceptance of Terms</h2>
            <p>By creating an account or using Forage ("the Service," "we," "us," or "our"), you agree to be bound by these Terms of Service. If you do not agree to all terms, do not use the Service. We reserve the right to modify these terms at any time. Continued use after changes constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">2. Not Medical Advice</h2>
            <p className="mb-3">Forage is a general-purpose nutrition and grocery planning tool. <strong className="text-text-primary">Nothing on this platform constitutes medical advice, dietary guidance from a licensed professional, or treatment for any health condition.</strong></p>
            <p className="mb-3">All calorie estimates, macro calculations, food identifications, and nutrition information generated by our AI are approximations only. Actual nutritional values vary significantly based on preparation method, portion size, brand, and other factors.</p>
            <p>You should consult a qualified healthcare provider, registered dietitian, or physician before making significant changes to your diet, especially if you have or suspect any medical condition including but not limited to diabetes, cardiovascular disease, eating disorders, food allergies, or kidney disease.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">3. AI-Generated Content Disclaimer</h2>
            <p className="mb-3">Forage uses artificial intelligence (powered by Anthropic's Claude) to analyze food photos, generate grocery lists, scan receipts, and provide nutrition estimates. By using these features you acknowledge:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>AI food identification and calorie estimates may be inaccurate, incomplete, or incorrect.</li>
              <li>AI-generated grocery lists are suggestions only and may not reflect current local store prices, availability, or product formulations.</li>
              <li>Receipt scan data may be misread, mis-categorized, or incorrectly tallied.</li>
              <li>AI responses in the grocery chat are not guaranteed to be accurate, current, or appropriate for your specific dietary needs.</li>
              <li>You are solely responsible for verifying any nutrition, pricing, or health information before acting on it.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">4. Eligibility</h2>
            <p>You must be at least 13 years old to use Forage. If you are under 18, you represent that you have parental or guardian consent. Users in the European Union must be at least 16 years old, or have verifiable parental consent. By using the Service you represent and warrant you meet these requirements.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">5. User Accounts</h2>
            <p className="mb-3">You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Provide accurate and truthful information when creating your account and during onboarding.</li>
              <li>Notify us immediately of any unauthorized use of your account.</li>
              <li>Not share your account with others or allow others to access the Service through your account.</li>
              <li>Not create multiple accounts to circumvent restrictions or bans.</li>
            </ul>
            <p className="mt-3">We reserve the right to suspend or terminate accounts that violate these terms, engage in fraudulent activity, or abuse the Service.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">6. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws or regulations.</li>
              <li>Attempt to reverse engineer, scrape, or exploit the Service or its underlying AI systems.</li>
              <li>Upload content that is illegal, harmful, threatening, obscene, or infringes on third-party rights.</li>
              <li>Use the Service to build a competing product or service.</li>
              <li>Attempt to gain unauthorized access to our systems, databases, or other users' data.</li>
              <li>Circumvent, disable, or interfere with security features of the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">7. User-Uploaded Content</h2>
            <p className="mb-3">You retain ownership of photos and content you upload (food photos, receipt images). By uploading content you grant Forage a limited, non-exclusive license to process and store that content solely to provide the Service to you.</p>
            <p>You represent that you have the right to upload any content you submit and that it does not violate any law or third-party rights. You must not upload images of other people without their consent, images containing sensitive personal information (such as credit card numbers or government IDs visible in receipt photos), or any illegal content.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">8. Pricing and Grocery Information</h2>
            <p>Store prices, product availability, and grocery recommendations generated by Forage are estimates based on general data and AI inference. We do not guarantee the accuracy of any price information. Prices vary by location, time, store, and product. Forage is not affiliated with, endorsed by, or partnered with any grocery retailer mentioned in generated lists.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">9. Third-Party Services</h2>
            <p>Forage integrates with third-party services including Supabase (data storage), Anthropic (AI), and Google (authentication). Your use of these services is also subject to their respective terms and privacy policies. We are not responsible for the practices, availability, or content of third-party services.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">10. Disclaimer of Warranties</h2>
            <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT ANY DEFECTS WILL BE CORRECTED. WE MAKE NO WARRANTY REGARDING THE ACCURACY OF CALORIE COUNTS, MACRO DATA, NUTRITIONAL INFORMATION, OR PRICE ESTIMATES.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">11. Limitation of Liability</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, FORAGE AND ITS OPERATORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO: health outcomes resulting from reliance on AI-generated nutrition data; financial decisions made based on grocery price estimates; allergic reactions or adverse health events related to food recommendations; data loss; or unauthorized access to your account. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE MONTHS PRECEDING THE CLAIM, OR $50, WHICHEVER IS GREATER.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">12. Indemnification</h2>
            <p>You agree to indemnify and hold harmless Forage and its operators from any claims, damages, losses, or expenses (including legal fees) arising from your use of the Service, violation of these Terms, or violation of any rights of a third party.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">13. Termination</h2>
            <p>You may delete your account at any time. We may suspend or terminate your access at any time, with or without cause, with or without notice. Upon termination, your right to use the Service ceases immediately. We may retain certain data as required by law or legitimate business purposes as described in our Privacy Policy.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">14. Governing Law</h2>
            <p>These Terms are governed by the laws of the United States and the state of Texas, without regard to conflict of law principles. Any disputes shall be resolved in the courts located in Texas, and you consent to personal jurisdiction in such courts.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-text-primary text-lg mb-3">15. Contact</h2>
            <p>For questions about these Terms, contact us at: <span className="text-lime">legal@forage.app</span></p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-border flex gap-4 text-sm">
          <Link href="/privacy" className="text-lime hover:text-lime-glow transition-colors">Privacy Policy</Link>
          <Link href="/" className="text-text-muted hover:text-text-secondary transition-colors">← Back to Forage</Link>
        </div>
      </div>
    </div>
  );
}
